/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.files;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JFrame;
import javax.swing.JTextArea;

/**
 *
 * @author Administrator
 */
public class JNotesFrame extends javax.swing.JFrame 
{
    Font myFont = new Font ("Times New Roman", Font.PLAIN, 22);
    
    String programNotes = "This program tracks U.S. Covid-19 statistics since 3-1-2020. The data is stored and retrieved from"
            + " a MYSQL database. A new date must follow the most recent entry. "
            + " "
            + " "
            + " battles with the Northwest Indian Federation in the early 1790s. \n\n"
            + "Seventeen states made up the Union at the time. Tennessee had been admitted in 1796 and Ohio in March of 1803 but no provisions had been made on how to change the flag."
            + " So even though the country had seventeen states Lewis & Clark carried a flag with fifteen stripes and fifteen stars. Because of this some still refer to it"
            + " as the Lewis & Clark flag.\n\n"
            + "This is also the flag immortalized by Francis Scott Key during the bombardment of Fort McHenry, Sept 13, 1814.";
      
    public JNotesFrame() 
    {
        initComponents();
        this.setLocationRelativeTo(this);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        // set color of text to teal
        JNotesTA.setForeground(new Color(0, 128 ,128));
        JNotesTA.setFont(myFont);
        // TextArea will not be edited
        JNotesTA.setEditable(false);
        JNotesTA.setLineWrap(true);
        JNotesTA.setWrapStyleWord(true);
        JNotesTA.setText(programNotes);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JNotesPagePnl = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JNotesTA = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JNotesPagePnl.setBackground(new java.awt.Color(102, 102, 102));

        JNotesTA.setColumns(20);
        JNotesTA.setRows(5);
        jScrollPane1.setViewportView(JNotesTA);

        javax.swing.GroupLayout JNotesPagePnlLayout = new javax.swing.GroupLayout(JNotesPagePnl);
        JNotesPagePnl.setLayout(JNotesPagePnlLayout);
        JNotesPagePnlLayout.setHorizontalGroup(
            JNotesPagePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JNotesPagePnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1006, Short.MAX_VALUE)
                .addContainerGap())
        );
        JNotesPagePnlLayout.setVerticalGroup(
            JNotesPagePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JNotesPagePnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JNotesPagePnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JNotesPagePnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JNotesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JNotesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JNotesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JNotesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JNotesFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JNotesPagePnl;
    private javax.swing.JTextArea JNotesTA;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
